### ISSUE TITLE
Handle tier info that comes after commodity_charge

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/RateParser#3]

**Comment by patwater** [comment]
Could you clarify a bit what this is regarding?  Maybe I'm not in the weeds of the tool though doesn't seem clear from the issue title.

**Comment by christophertull** [comment]
Yeah more a mental reminder for myself. Refers to the physical ordering of the components in the file. Ideally the ordering should not matter. e.g.

```yaml
tier_prices:
      - 1.49
      - 1.70
      - 2.62
      - 4.38
      - 9.17
commodity_charge: Budget
```

should be just as valid as

```yaml
commodity_charge: Budget
tier_prices:
      - 1.49
      - 1.70
      - 2.62
      - 4.38
      - 9.17
```
