### ISSUE TITLE
Tier prices as formulas

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/RateParser#7]
Should support tier prices as formulas. For example:

```yaml
elevation_surcharge:
  depends_on: pressure_zone
  values:
    1: 0
    2: 1.2
tier_prices:
  - 3.12 + elevation_surcharge
```

**Comment by christophertull** [comment]
This is already covered in a different manner:

```yaml
   elevation_rate:
      depends_on: zones
      values:
        1: 0.00
        2: 0.44
        3: 1.03
        4: 1.64
    elevation_charge: elevation_rate*usage_ccf
    bill: commodity_charge+service_charge+elevation_charge
```
