### ISSUE TITLE
Better support for numeric maps

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/RateParser#9]
Instead of just simple maps, RateParser should also be able to support ranges and "ad infinitum" values in maps. For example:

```yaml
numeric_charge:
  depends_on: numeric_value
  values:
  1-4: 33
  5-8: 55
  9+: 99
```
